TransactionTracker/models.py
import datetime
import django
from django.db import models
from tastypie.utils.timezone import now

# Create your models here.
from django.db.models import Model
from django.contrib.auth.models import User
from django.contrib import admin


class transaction_type(Model):
    description = django.db.models.CharField(max_length=50)
    multiplier = django.db.models.DecimalField(max_digits=12, decimal_places=3)
    owed_multiplier = django.db.models.DecimalField(decimal_places=3, max_digits=12)

    def __str__(self):
        return self.description


class transaction(Model):
    description = django.db.models.CharField(max_length=100)
    date = django.db.models.DateField()
    amount = django.db.models.DecimalField(max_digits=12, decimal_places=2)
    transaction_type = django.db.models.ForeignKey(transaction_type)
    user = django.db.models.ForeignKey(User)

    def __unicode__(self):
        return self.description

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.date.today()

        return super(transaction, self).save(*args, **kwargs)

admin.site.register(transaction_type)

TransactionTracker/forms.py
from django import forms
from django.contrib.auth.models import User
from TransactionTracker.models import transaction_type


class EntryForm(forms.Form):
    user = forms.ModelChoiceField(label="User",
                                  queryset=User.objects.all(),
                                  initial=0,
                                  widget=forms.Select(
                                      attrs={'class': 'form-control'}))

    type = forms.ModelChoiceField(label="Type",
                                  queryset=transaction_type.objects.all(),
                                  initial=0,
                                  widget=forms.Select(
                                      attrs={'class': 'form-control'}
                                  ))

    amount = forms.DecimalField(decimal_places=2,
                                widget=forms.TextInput(
                                    attrs={"class": "form-control"}))

    description = forms.CharField(max_length=50,
                                  widget=forms.TextInput(
                                      attrs={"class": "form-control"}
                                  ))

TransactionTracker/views.py
# Create your views here.
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
import datetime

from TransactionTracker.forms import EntryForm
from TransactionTracker.models import transaction, transaction_type


def debt(request):
    return render(request, 'debt.html')


def transactions(request):
    return render(request, 'transactions.html')


def home(request):

    return render(request, 'index.html')

    # transactions = transaction.objects.all()
    #
    # users = {1: {'paid': 0, 'owed': 0},
    #          2: {'paid': 0, 'owed': 0}}
    #
    # for trans in transactions:
    #     if not trans.user.username in users:
    #         users[trans.user.username] = {'paid': 0, 'owed': 0}
    #
    #     users[trans.user.username]['paid'] += trans.amount
    #     users[trans.user.username]['owed'] += trans.amount * trans.transaction_type.multiplier
    #
    # u2sum = users['Tom']['owed']
    # u1sum = users['Sean']['owed']
    #
    # users['diff'] = u1sum - u2sum
    #
    # money = users
    #
    # return render(request, 'home.html', {"money": money})


def view(request):
    all_trans = transaction.objects.order_by('-date').all()

    return render(request, 'view.html', {'transactions': all_trans})


def add(request):
    return render(request, 'add.html')

    # #adding new transaction
    # if request.method == "POST":
    #     transaction_form = EntryForm(request.POST)
    #     if transaction_form.is_valid():
    #         user = User.objects.get(pk=transaction_form.data['user'])
    #         trans_type = transaction_type.objects.get(pk=transaction_form.data['type'])
    #
    #         trans = transaction(user=user,
    #                             amount=transaction_form.data['amount'],
    #                             description=transaction_form.data['description'],
    #                             transaction_type=trans_type)
    #
    #         trans.date = datetime.date.today()
    #         trans.save()
    #
    # transaction_form = EntryForm()
    #
    # return render(request, 'add.html', {'t_form': transaction_form})

TransactionTracker/templates/add.html
{% extends "base.html" %}

{% block Content %}

    <form action="{% url "add" %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_user" class="control-label col-lg-2">User</label>
            <div class=col-lg-2>
                {{ t_form.user }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_type" class="control-label col-lg-2">Type</label>
            <div class="col-lg-2">
                {{ t_form.type }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_amount" class="control-label col-lg-2">Amount</label>
            <div class="col-lg-2">
                {{ t_form.amount }}
            </div>
        </div>
        <div class="form-group">
            <label for="id_description" class="control-label col-lg-2">Note</label>
            <div class="col-lg-2">
                {{ t_form.description }}
                <button type="submit" class="btn btn-primary" style="margin-top:10px;">Submit</button>
            </div>
        </div>
    </form>

{% endblock Content %}

TransactionTracker/templates/add2.html
{% extends "base.html" %}

{% block Content %}

    <form action="{% url "add" %}" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_user" class="control-label col-lg-2">User</label>
            <div class=col-lg-2>
                {{ t_form.user }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_type" class="control-label col-lg-2">Type</label>
            <div class="col-lg-2">
                {{ t_form.type }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_amount" class="control-label col-lg-2">Amount</label>
            <div class="col-lg-2">
                {{ t_form.amount }}
            </div>
        </div>
        <div class="form-group">
            <label for="id_description" class="control-label col-lg-2">Note</label>
            <div class="col-lg-2">
                {{ t_form.description }}
                <button type="submit" class="btn btn-primary" style="margin-top:10px;">Submit</button>
            </div>
        </div>
    </form>

{% endblock Content %}

TransactionTracker/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{{ MEDIA_URL }}bootstrap.min.js"></script>
    <link rel='stylesheet' href="{{ MEDIA_URL }}bootstrap.min.css" media="screen"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Payment Tracker</title>
</head>
<body>

    <div class="navbar navbar-static-top navbar-inverse">
        <div class="container">
            <a href="../" class="navbar-brand">Payment Tracker</a>
            <ul class="nav navbar-nav">
                <li>
                    <a href="../">Home</a>
                </li>
                <li>
                    <a href="{% url "view" %}">View Transactions</a>
                </li>
                <li>
                    <a href="{% url "add" %}">Add Transaction</a>
                </li>
            </ul>
        </div>
    </div>

    <div class='container '>
        {% block Content %}

        {% endblock Content %}
    </div>


</body>
</html>

TransactionTracker/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block Content %}
    <p>
        Tom owes Sean: {{ money.diff }}
    </p>

{% endblock Content %}

TransactionTracker/templates/view.html
{% extends "base.html" %}

{% block Content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>
                User
            </th>
            <th>
                For
            </th>
            <th>
                Description
            </th>
            <th>
                Amount
            </th>
            <th>
                Date
            </th>
        </tr>
        </thead>
        <tbody>
        {% for trans in transactions %}
            <tr>
                <td>
                    {{ trans.user }}
                </td>
                <td>
                    {{ trans.transaction_type }}
                </td>
                <td>
                    {{ trans.description }}
                </td>
                <td>
                    {{ trans.amount }}
                </td>
                <td>
                    {{ trans.date }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}